import { INotificationAction } from '../interfaces/main.notif.interfaces';
export declare enum NOTIF_ENUM {
    TASK_ASSIGNED = "TASK_ASSIGNED",
    TASK_UPDATED = "TASK_UPDATED",
    TASK_COMPLETED = "TASK_COMPLETED",
    TASK_CANCELLED = "TASK_CANCELLED",
    TASK_DUE_SOON = "TASK_DUE_SOON",
    TASK_OVERDUE = "TASK_OVERDUE",
    SYSTEM_ALERT = "SYSTEM_ALERT",
    GENERAL_NOTIFICATION = "GENERAL_NOTIFICATION",
    WELCOME_MESSAGE = "WELCOME_MESSAGE",
    PASSWORD_RESET = "PASSWORD_RESET",
    TASK_PAUSED = "TASK_PAUSED",
    TASK_RESUMED = "TASK_RESUMED"
}
export declare const NOTIF_ACTION: Record<NOTIF_ENUM, INotificationAction>;
