import { EventEmitter } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { LoadingService } from '../../services';
import * as i0 from "@angular/core";
export declare class CustomConfirmPopupComponent {
    private sanitizer;
    loadingService: LoadingService;
    message: string;
    type: 'info' | 'delete';
    confirmButtonText: string;
    cancelButtonText: string;
    extraButton: string;
    confirmTitle: string;
    confirmEvent: EventEmitter<any>;
    cancelEvent: EventEmitter<void>;
    extraEvent: EventEmitter<void>;
    overlayClicked: EventEmitter<boolean>;
    successMsg: import("@angular/core").InputSignal<string>;
    checkedInfoSvg: SafeHtml;
    checkIcon: SafeHtml;
    closeSvg: SafeHtml;
    currentView: 'confirmation' | 'success';
    successAnimationState: 'hidden' | 'visible';
    successPressed: boolean;
    isVisible: boolean;
    eventVal: any;
    private _showSuccessScreen;
    set showSuccessScreen(value: boolean);
    get showSuccessScreen(): boolean;
    constructor(sanitizer: DomSanitizer, loadingService: LoadingService);
    ngOnInit(): void;
    private watchSuccessScreen;
    ngOnChanges(): void;
    open(event?: any): void;
    close(): void;
    checkSuccess(): void;
    private transitionToSuccess;
    onOverlayClick(event: MouseEvent): void;
    startAnimation(event: any): void;
    doneAnimation(event: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomConfirmPopupComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomConfirmPopupComponent, "custom-confirm-popup", never, { "message": { "alias": "message"; "required": true; }; "type": { "alias": "type"; "required": true; }; "confirmButtonText": { "alias": "confirmButtonText"; "required": false; }; "cancelButtonText": { "alias": "cancelButtonText"; "required": false; }; "extraButton": { "alias": "extraButton"; "required": false; }; "confirmTitle": { "alias": "confirmTitle"; "required": false; }; "successMsg": { "alias": "successMsg"; "required": false; "isSignal": true; }; "showSuccessScreen": { "alias": "showSuccessScreen"; "required": false; }; }, { "confirmEvent": "confirmEvent"; "cancelEvent": "cancelEvent"; "extraEvent": "extraEvent"; "overlayClicked": "overlayClicked"; }, never, never, true, never>;
}
