import { EventEmitter } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { IComponentFormError } from '../../interfaces';
import * as i0 from "@angular/core";
export declare class CustomCalenderFormComponent {
    label: string;
    placeholder: string;
    labelClass: string;
    calendarPopUpClass: string;
    calendarInputClass: string;
    calendarContainerClass: string;
    componentClass: string;
    minDate: Date | null;
    maxDate: Date | null;
    controlName: string;
    parentForm: FormGroup;
    validation: IComponentFormError[];
    name: string;
    disabled: boolean;
    valueChange: EventEmitter<Date | null>;
    showCalendarForm: boolean;
    currentMonth: Date;
    days: Date[];
    weekdays: string[];
    private _value;
    private onChange;
    private onTouched;
    constructor();
    ngOnInit(): void;
    get value(): Date | null;
    set value(val: Date | null);
    writeValue(value: Date | null): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    toggleCalendar(): void;
    prevMonth(): void;
    nextMonth(): void;
    generateCalendar(): void;
    selectDate(date: Date): void;
    private normalizeToMidnightUTC;
    private applyDate;
    isSelected(date: Date): boolean;
    isCurrentMonth(date: Date): boolean;
    isDisabled(date: Date): boolean;
    getMonthName(): string;
    getYear(): number;
    formatDisplayDate(): string;
    containRequiredError(): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomCalenderFormComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomCalenderFormComponent, "custom-calender-form", never, { "label": { "alias": "label"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "labelClass": { "alias": "labelClass"; "required": false; }; "calendarPopUpClass": { "alias": "calendarPopUpClass"; "required": false; }; "calendarInputClass": { "alias": "calendarInputClass"; "required": false; }; "calendarContainerClass": { "alias": "calendarContainerClass"; "required": false; }; "componentClass": { "alias": "componentClass"; "required": false; }; "minDate": { "alias": "minDate"; "required": false; }; "maxDate": { "alias": "maxDate"; "required": false; }; "controlName": { "alias": "controlName"; "required": true; }; "parentForm": { "alias": "parentForm"; "required": true; }; "validation": { "alias": "validation"; "required": true; }; "name": { "alias": "name"; "required": true; }; "disabled": { "alias": "disabled"; "required": false; }; }, { "valueChange": "valueChange"; }, never, never, true, never>;
}
